In [ ]:
import numpy as np

In [ ]:
arr = np.arange(6)
print(arr)
print(arr.reshape(2, 3))
print(arr.reshape(3, 2))

# [0 1 2 3 4 5]
# [[0 1 2]
#  [3 4 5]]
# [[0 1]
#  [2 3]
#  [4 5]]

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.flatten())
print(arr.T)

# [1 2 3 4 5 6]
# [[1 4]
#  [2 5]
#  [3 6]]

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.ravel())
print(arr.shape)
print(arr.T.shape)

# [1 2 3 4 5 6]
# (3,2)
# (2,3)

[1 2 3 4 5 6]
(3, 2)
(2, 3)


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate([a, b]))

c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
print(np.concatenate([c, d]))

# [1 2 3 4 5 6]
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
print(np.concatenate([c, d], axis=1))

# [[1 2 5 6]
#  [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.vstack([a, b]))
print(np.hstack([a, b]))

# [[1 2 3]
#  [4 5 6]]
# [1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
