In [2]:
import numpy as np

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[1:4])
print(arr[:3])
print(arr[::2])

# 10
# 50
# 20 30 40
# 10 20 30
# 10 30 50

10
50
[20 30 40]
[10 20 30]
[10 30 50]


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0])
print(arr2d[0][1])
print(arr2d[0, 1])
print(arr2d[1, 2])

# [1 2 3]
# 2
# 2
# 6

[1 2 3]
2
2
6


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[:, 0])
print(arr2d[0, :])
print(arr2d[1:, 1:])

# [1 4 7]
# [1 2 3]
# [[5 6]
#  [8 9]]

[1 4 7]
[1 2 3]
[[5 6]
 [8 9]]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[0] = 100
print(arr)
arr[1:3] = [200, 300]
print(arr)

# [100 2 3 4 5]
# [100 200 300 4 5]

[100   2   3   4   5]
[100 200 300   4   5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3
print(mask)
print(arr[mask])
print(arr[arr % 2 == 0])

# [False , False, False , True, True, True ]
# [4 5 6]
# [2 4 6]

[False False False  True  True  True]
[4 5 6]
[2 4 6]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 2, 4]])
print(arr[[1, 1, 3]])

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[[0, 2]])

# [10 30 50]
# [20 20 40]
# [[1 2 3]
#  [7 8 9]]

[10 30 50]
[20 20 40]
[[1 2 3]
 [7 8 9]]


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[[0, 1], [0, 1]])
print(arr2d[[0, 2], [1, 2]])

# [[1 2]
#  [4 5]]

# [[2 3]
#  [8 9]]

[1 5]
[2 9]


#  Paired Fancy Indexing on Rows and Columns

```python
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2d[[0, 1], [0, 1]])
```

### Output

```text
[1 5]
```

### Why?

When **two lists** are used for rows and columns, NumPy pairs them element-by-element, similar to `zip()`.

```text
(row=0, col=0) → arr2d[0, 0] → 1
(row=1, col=1) → arr2d[1, 1] → 5
```

So the result is:

```text
[1 5]
```

It is **not** a `2 × 2` matrix.

Another example:

```python
print(arr2d[[0, 2], [1, 2]])
```

Output:

```text
[2 9]
```

because:

```text
(0, 1) → 2
(2, 2) → 9
```

### If You Want All Combinations

Use `np.ix_()`:

```python
print(arr2d[np.ix_([0, 1], [0, 1])])
```

Output:

```text
[[1 2]
 [4 5]]
```

###  Key Takeaway

```python
arr2d[[0, 1], [0, 1]]
```

→ **pairs coordinates**

```text
(0,0), (1,1)
```

Whereas:

```python
arr2d[np.ix_([0, 1], [0, 1])]
```

→ **all row-column combinations**

> **Two fancy-index lists are paired element-by-element, not combined into a rectangular block.**

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[-1])
print(arr2d[-1, -1])
print(arr2d[:-1])
print(arr2d[:, -1])

# [[7 8 9]
#  [4 5 6]
#  [1 2 3]]

# 9


# [3 6 9]

[7 8 9]
9
[[1 2 3]
 [4 5 6]]
[3 6 9]


#  Negative Indexing on 2D Arrays

```python
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
```

## 1. `arr2d[-1]`

```python
print(arr2d[-1])
```

Output:

```text
[7 8 9]
```

`-1` means the **last row**.

It does **not** reverse the array.

```text
arr2d[-1] → last row
```

---

## 2. `arr2d[-1, -1]`

```python
print(arr2d[-1, -1])
```

Output:

```text
9
```

This means:

```text
-1 → last row
-1 → last column
```

So it selects the bottom-right element.

---

## 3. `arr2d[:-1]`

```python
print(arr2d[:-1])
```

Output:

```text
[[1 2 3]
 [4 5 6]]
```

Here `:-1` is a **slice** meaning:

> Everything up to, but not including, the last row.

---

## 4. `arr2d[:, -1]`

```python
print(arr2d[:, -1])
```

Output:

```text
[3 6 9]
```

Meaning:

```text
:  → all rows
-1 → last column
```

###  Important Distinction

```python
arr2d[-1]      # last row
arr2d[:-1]     # all rows except last
arr2d[:, -1]   # last column
arr2d[-1, -1]  # last element
```

> **`-1` as an index selects the last item.**

> **`:-1` as a slice selects everything except the last item.**

In [ ]:
 arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr[(arr > 2) & (arr < 7)])
print(arr[(arr < 3) | (arr > 6)])

# [3 4 5 6]
# [1 2 7 8]

[3 4 5 6]
[1 2 7 8]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
fancy = arr[[0, 1, 2]]
fancy[0] = 999
print(arr)
print(fancy)

sliced = arr[0:3]
sliced[0] = 888
print(arr)
print(sliced)

# [10 20 30 40 50]
# [999 20 30]
# [10 20 30 40 50]
# [888 20 30]

[10 20 30 40 50]
[999  20  30]
[888  20  30  40  50]
[888  20  30]


# Fancy Indexing vs Basic Slicing: View vs Copy

```python
arr = np.array([10, 20, 30, 40, 50])
```

## 1. Fancy Indexing → Copy

```python
fancy = arr[[0, 1, 2]]

fancy[0] = 999

print(arr)
print(fancy)
```

Output:

```text
[10 20 30 40 50]
[999  20  30]
```

Fancy indexing creates a **copy**, so modifying `fancy` does **not** affect `arr`.

---

## 2. Basic Slicing → View

```python
sliced = arr[0:3]

sliced[0] = 888

print(arr)
print(sliced)
```

Output:

```text
[888  20  30  40  50]
[888  20  30]
```

Basic slicing creates a **view**, which shares the underlying memory with `arr`.

Therefore, modifying `sliced` also modifies `arr`.

---

##  The Most Important Rule

| Operation | Returns | Changes original? |
|-----------|---------|-------------------|
| `arr[0:3]` | **View** | ✅ Yes |
| `arr[[0,1,2]]` | **Copy** | ❌ No |
| `arr[mask]` | **Copy** | ❌ No |

### Mental Model

```text
Basic slicing
arr[0:3]
    ↓
  VIEW
    ↓
Shares memory with arr
```

```text
Fancy indexing
arr[[0,1,2]]
    ↓
  COPY
    ↓
Independent data
```

This is similar to the `reshape()` view behavior:

> **Slicing → usually shares data**

> **Fancy indexing → creates a copy**

### Example

If you need an independent copy from a slice:

```python
sliced = arr[0:3].copy()
```

Now modifying `sliced` will not affect `arr`.

> **Remember: `:` slicing → view, fancy/boolean indexing → copy.**

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr[arr > 3] = 0
print(arr)

arr2 = np.array([[1, 2], [3, 4], [5, 6]])
arr2[arr2 > 3] = -1
print(arr2)

[1 2 3 0 0]
[[ 1  2]
 [ 3 -1]
 [-1 -1]]


# Boolean Mask Assignment

```python
arr = np.array([1, 2, 3, 4, 5])

arr[arr > 3] = 0

print(arr)
```

### Output

```text
[1 2 3 0 0]
```

`arr > 3` creates a Boolean mask:

```text
[False False False True True]
```

Using the mask for assignment:

```python
arr[arr > 3] = 0
```

means:

> Wherever the condition is `True`, replace the value with `0`.

This modifies the original array **in place**.

### 2D Example

```python
arr2 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])

arr2[arr2 > 3] = -1

print(arr2)
```

Output:

```text
[[ 1  2]
 [ 3 -1]
 [-1 -1]]
```

###  Key Takeaway

```python
arr[condition] = value
```

→ replaces every element where `condition` is `True`.

This is a powerful way to perform **conditional replacement without loops**.

In [ ]:
arr = np.array([1, -2, 3, -4, 5, -6])
print(np.where(arr > 0))
print(np.where(arr > 0, arr, 0))

# [0 2 4]
# [1 0 3 0 5 0]

(array([0, 2, 4]),)
[1 0 3 0 5 0]


In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(arr2d[::2])
print(arr2d[::2, ::2])
print(arr2d[10:20])

# [[1 2 3]
#  [7 8 9]]

# [[1 3]
#  [7 9]]



[[1 2 3]
 [7 8 9]]
[[1 3]
 [7 9]]
[]


In [ ]:
arr = np.arange(10)
view1 = arr[2:8]
view2 = view1[1:4]
view2[0] = 999
print(arr)

# [999 4 5]


[  0   1   2 999   4   5   6   7   8   9]


#  Chained Views in NumPy

```python
arr = np.arange(10)

view1 = arr[2:8]
view2 = view1[1:4]

view2[0] = 999

print(arr)
```

### Output

```text
[  0   1   2 999   4   5   6   7   8   9]
```

### Why?

First:

```python
view1 = arr[2:8]
```

`view1` is a **view** of `arr`.

Then:

```python
view2 = view1[1:4]
```

`view2` is also a **view**, so it still shares memory with the original `arr`.

The indexing relationship is:

```text
arr
 ↓
view1 = arr[2:8]
 ↓
view2 = view1[1:4]
```

`view2[0]` corresponds to:

```text
view1[1]
     ↓
arr[3]
```

Therefore:

```python
view2[0] = 999
```

changes:

```python
arr[3]
```

to `999`.

###  Key Takeaway

> **Slicing a view creates another view, not a copy.**

So views can be chained, and a modification at the end of the chain can still modify the original array.

If you need an independent array:

```python
copy = view2.copy()
```

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_mask = arr2d[:, 0] > 3
print(row_mask)
print(arr2d[row_mask])
print(arr2d[row_mask, 1])

# [[False]
#  [True]
#  [True]]

# [[1]
#  [4]
#  [7]]

[False  True  True]
[[4 5 6]
 [7 8 9]]
[5 8]


#Boolean Mask Built from a Column

```python
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

row_mask = arr2d[:, 0] > 3

print(row_mask)
```

### Output

```text
[False  True  True]
```

First:

```python
arr2d[:, 0]
```

selects the first column:

```text
[1 4 7]
```

Then:

```python
[1 4 7] > 3
```

produces:

```text
[False True True]
```

The mask is **1D** because `arr2d[:, 0]` is 1D.

---

## Use the Mask to Select Rows

```python
print(arr2d[row_mask])
```

Output:

```text
[[4 5 6]
 [7 8 9]]
```

The mask selects **entire rows** where the mask is `True`.

---

## Select a Specific Column from Those Rows

```python
print(arr2d[row_mask, 1])
```

Output:

```text
[5 8]
```

Here:

```text
row_mask → selects rows 1 and 2
1        → selects column 1
```

###  Key Takeaway

A mask created from one column:

```python
arr2d[:, 0] > 3
```

is a **1D row-level mask**.

```python
arr2d[row_mask]
```

→ selects entire rows.

```python
arr2d[row_mask, 1]
```

→ selects column `1` only from those rows.

In [3]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[arr2d > 5])

# [6 7 8 9]

[6 7 8 9]


In [4]:
arr = np.array([1, 2, 3, 4, 5])
arr[[0, 2, 4]] = 0
print(arr)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2[:, 1] = 100
print(arr2)

# [0 2 0 4 0]
# [[1 100 3]
#  [4 100 6]]

[0 2 0 4 0]
[[  1 100   3]
 [  4 100   6]]


In [5]:
arr = np.array([1, 2, 3, 4, 5])
def modify(a):
    a[0] = 999

modify(arr[1:4])
print(arr)

modify(arr[[1, 2, 3]])
print(arr)

# [1 999 3 4 5]
# [1 2 3 4 5]

[  1 999   3   4   5]
[  1 999   3   4   5]


# View vs. Copy Through a Function Call

```python
arr = np.array([1, 2, 3, 4, 5])

def modify(a):
    a[0] = 999
```

## 1. Passing a Slice

```python
modify(arr[1:4])
print(arr)
```

Output:

```text
[1 999 3 4 5]
```

Why?

```python
arr[1:4]
```

is a **slice → view**.

So the function receives a view that shares memory with `arr`.

```text
arr[1:4] → [2 3 4]
              ↓
          modify(a)
              ↓
          a[0] = 999
              ↓
          changes arr[1]
```

---

## 2. Passing Fancy Indexing

```python
modify(arr[[1, 2, 3]])
print(arr)
```

Output:

```text
[1 999 3 4 5]
```

```python
arr[[1, 2, 3]]
```

is **fancy indexing → copy**.

Therefore, `modify()` changes only the independent copy.

It does **not** change `arr` further.

###  Important

The second operation does **not reset** the previous `999`.

It simply makes **no additional change** to `arr`.

> **Slice → view → function can modify original**

> **Fancy indexing → copy → function cannot modify original**

In [6]:
arr = np.array([10, 20, 30, 40, 50])
a = arr[2]
b = arr[[2]]
print(a, type(a))
print(b, type(b), b.shape)

30 <class 'numpy.int64'>
[30] <class 'numpy.ndarray'> (1,)

30 <class 'numpy.int64'>
[30] <class 'numpy.ndarray'> (1,)


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[::-1][:3])
print(arr[arr > 5][::-1])

# [10 9 8 7 6 5 4 3 2 1]
# [10 9 8 7 6]

[10  9  8]
[10  9  8  7  6]


# Chained Slicing

Given:

```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
```

Consider:

```python
print(arr[::-1][:3])
```

Work from **left to right**.

### Step 1 — Reverse

```python
arr[::-1]
```

Output:

```text
[10 9 8 7 6 5 4 3 2 1]
```

### Step 2 — Take the First 3

```python
[::-1][:3]
```

The `[:3]` is applied to the **reversed result**:

```text
[10 9 8]
```

### Final Output

```text
[10 9 8]
```

---

## Another Example

```python
print(arr[arr > 5][::-1])
```

First filter:

```text
[6 7 8 9 10]
```

Then reverse:

```text
[10 9 8 7 6]
```

###  Key Takeaway

For chained operations:

```python
operation1[operation2]
```

always follow the operations **from left to right**.

> **Each operation works on the result produced by the previous operation.**