# NumPy Broadcasting — Basic Rule

**Broadcasting** allows NumPy to perform operations between arrays with different shapes.

### Broadcasting Rule

NumPy compares shapes **from right to left**.

Two dimensions are compatible when:

- They are **equal**, or
- One of them is **1**, or
- One dimension is **missing**

---

### Example

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)
```

Shapes:

```text
a → (2, 3)
b →    (3,)
```

Align them from the right:

```text
a: 2  3
b:    3
```

The rightmost dimensions match:

```text
3 == 3  → compatible
```

The missing dimension of `b` is treated as `1`, so conceptually:

```text
b → (1, 3)
```

NumPy broadcasts `b` across every row:

```text
[1 2 3]   +   [10 20 30]
[4 5 6]   +   [10 20 30]
```

### Output

```text
[[11 22 33]
 [14 25 36]]
```

---

### When Does Broadcasting Fail?

For example:

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20])
```

Shapes:

```text
a: 2  3
b:    2
```

Compare from the right:

```text
3 ≠ 2
```

Neither dimension is `1`, so the shapes are **not compatible**.

Therefore:

```python
a + b
```

raises a `ValueError`.

###  Key Takeaway

> **Compare dimensions from right to left. Each pair must be equal, or one of them must be `1`, or one dimension must be missing.**

In [ ]:
import numpy as np

In [ ]:
a = np.array([[5], [10]])          # shape (2, 1)
b = np.array([1, 2, 3])            # shape (3,)

# [[6 7 8]
# [11 12 13]]

In [ ]:
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

# [[11 12 13]
#   [21 22 23]
#   [31 32 33]]

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])   # shape (2, 3)
b = np.array([100])                     # shape (1,)

# [[101 102 103]
#  [104 105 106]]

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])   # shape (3, 2)
b = np.array([1, 0])                      # shape (2,)
# [2 2]
# [4 4]
# [6 6]

In [ ]:
a = np.array([[1, 2, 3]])     # shape (1, 3)
b = np.array([[10], [20]])    # shape (2, 1)

# [[11 12 13]
#   [21 22 23]]

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])   # shape (2, 3)
b = np.array([1, 2])                    # shape (2,)

# Error

In [ ]:
a = np.arange(24).reshape(2, 3, 4)   # shape (2, 3, 4)
b = np.array([1, 2, 3, 4])            # shape (4,)

# [[[ 1,  3,  5,  7],
#         [ 5,  7,  9, 11],
#         [ 9, 11, 13, 15]],

#        [[13, 15, 17, 19],
#         [17, 19, 21, 23],
#         [21, 23, 25, 27]]]

In [ ]:
a = np.array([1, 2, 3, 4])        # shape (4,)
b = a[:, np.newaxis]              # what shape is this?

# b-(4,1)
# this will add a and b forming matrix of (4, 4)


In [ ]:
a = np.zeros((5, 1, 3))     # shape (5, 1, 3)
b = np.zeros((1, 4, 3))     # shape (1, 4, 3)

# shape of result will be (5,4,3)

In [ ]:
a = np.array([[1, 2, 3]])      # shape (1, 3)
b = np.array([[1], [2], [3]])  # shape (3, 1)
c = np.array([10, 20, 30])      # shape (3,)

result = a + b + c
# shape will be (3,3)

In [ ]:
a = np.ones((8, 1, 6, 1))
b = np.ones((7, 1, 5))

# (8,7,6,5)

In [ ]:
a = np.ones((6, 1))
b = np.ones((1, 8))
c = np.ones((6, 8, 1))

# Error

In [ ]:
a = np.ones((3, 4, 5))
b = np.ones((4, 5))
c = np.ones((5,))

result = a * b * c

# it will result in (3,4,5)

In [ ]:
a = np.ones((2, 1, 4))
b = np.ones((3, 4))
c = np.ones((2, 3, 1))

result = a + b + c

# shape will be (2,3,4)