In [ ]:
import numpy as np

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))
print(arr.shape)
print(arr.ndim)

# [1 2 3 4 5]
# <class 'numpy_array'>
# (5,0)
# 1D

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1


### Explanation

**`type(arr)`**: returns `<class 'numpy.ndarray'>`. `ndarray` means **n-dimensional array**, which is the main array type used by NumPy.

**`.shape`**: returns a **tuple** showing the size of each dimension. For a 1D array containing 5 elements, the shape is `(5,)`. The comma is important because `(5,)` is a one-element tuple. It is not `(5, 0)` because there is only **one dimension**.

**`.ndim`**: returns the **number of dimensions** as an integer. So here it returns `1`, not `"1D"`.

In [ ]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
print(arr2d.shape)
print(arr2d.ndim)
print(arr2d.size)

# [[1 2 3],
#  [4 5 6]]
# (2,3)
# 2D
# 6

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6


### Explanation

**`.shape`**: `(2, 3)` means the array has **2 rows and 3 columns**.

**`.ndim`**: returns `2` because the array has **2 dimensions**. It returns the integer `2`, not `"2D"`.

**`.size`**: returns the **total number of elements**. Here, `2 × 3 = 6`, so the size is `6`.

NumPy displays a 2D array with rows on separate lines and **without commas** between elements.

In [ ]:
print(np.zeros((2, 3)))
print(np.ones((3, 2)))
print(np.eye(3))

# [[0.0 0.0 0.0],
#  [0.0 0.0 0.0]]

# [[1.0 1.0]
#  [1.0 1.0]
#  [1.0 1.0]]

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Explanation

**`np.zeros((2, 3))`** creates a `2 × 3` array filled with `0`.

**`np.ones((3, 2))`** creates a `3 × 2` array filled with `1`.

**`np.eye(3)`** creates a **3 × 3 identity matrix**. It has `1`s on the main diagonal and `0`s everywhere else.

NumPy normally prints array elements **without commas**. Also, `0.` and `1.` are floating-point values, so NumPy does not need to print the trailing zero.

```text
Python list  → [1.0, 2.0, 3.0]
NumPy array  → [1. 2. 3.]

In [ ]:
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))

# [0 2 4 6 8]
# [0.0 0.25 0.5 0.75 1.]

[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


### Explanation

**`np.arange(start, stop, step)`** creates values using a specified **step size**. The `stop` value is not included.

For example, `np.arange(0, 10, 2)` gives:

`[0 2 4 6 8]`

**`np.linspace(start, stop, num)`** creates an exact **number of evenly spaced values**. By default, both the start and stop values are included.

For example, `np.linspace(0, 1, 5)` gives:

`[0.   0.25 0.5  0.75 1.  ]`

The main difference is:

- `arange()` → specify the **step size**
- `linspace()` → specify the **number of values**

In [ ]:
arr = np.array([1, 2, 3])
print(arr.dtype)

arr2 = np.array([1.0, 2, 3])
print(arr2.dtype)

arr3 = np.array([1, 2, 3], dtype=float)
print(arr3.dtype)
print(arr3)

# int
# float
# float
# [1. 2. 3.]

int64
float64
float64
[1. 2. 3.]


### Explanation

**`.dtype`** tells us the **data type of the elements** in a NumPy array.

NumPy uses specific dtypes such as `int64`, `int32`, `float64`, and `float32`, instead of simply `int` or `float`.

NumPy arrays are **homogeneous**, which means all elements normally have the same dtype.

For example:

```python
np.array([1.0, 2, 3])

In [ ]:
print(np.full((2, 3), 7))
print(np.arange(12).reshape(3, 4))

# [[0 1 2 3],
#  [4 5 6 7],
#  [8 9 10 11]]

[[7 7 7]
 [7 7 7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]




## 1. `np.full()`

```python
print(np.full((2, 3), 7))
```

### Output

```text
[[7 7 7]
 [7 7 7]]
```

### Explanation

`np.full(shape, value)` creates a NumPy array with the specified **shape** and fills every element with the given **value**.

```python
np.full((2, 3), 7)
```

- `(2, 3)` → 2 rows and 3 columns
- `7` → value used to fill every element

### Remember

| Function | Purpose |
|----------|---------|
| `np.zeros()` | Creates an array filled with `0` |
| `np.ones()` | Creates an array filled with `1` |
| `np.full()` | Creates an array filled with a specified value |
| `np.eye()` | Creates an identity matrix |

---

## 2. `np.arange()` with `reshape()`

```python
print(np.arange(12).reshape(3, 4))
```

### Output

```text
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
```

### Explanation

`np.arange(12)` creates values from `0` up to, but not including, `12`:

```text
[0 1 2 3 4 5 6 7 8 9 10 11]
```

Then:

```python
.reshape(3, 4)
```

reshapes those **12 elements** into:

- 3 rows
- 4 columns

Since:

> `3 × 4 = 12`

the reshape is valid.

### Important NumPy Printing Rule

NumPy's default array output does **not** use commas between elements or rows.

 Python-list style:

```text
[[0, 1, 2, 3],
 [4, 5, 6, 7]]
```

 NumPy style:

```text
[[0 1 2 3]
 [4 5 6 7]]
```

NumPy also aligns numbers in columns, which is why values such as `0`, `1`, and `10` may have slightly different spacing.

### Key Takeaway

> **`np.full(shape, value)` → creates an array filled with a specified value.**

> **`reshape(rows, columns)` → changes the shape without changing the data.**

In [ ]:
arr = np.array([1, 2, 3, "4"])
print(arr)
print(arr.dtype)

arr2 = np.array([True, False, True])
print(arr2.dtype)

arr3 = np.array([1, 2, 3], dtype=np.int8)
print(arr3.dtype)
print(arr3.itemsize)

# [1 2 3 '4']
# str
# bool
# int8
# 3

['1' '2' '3' '4']
<U21
bool
int8
1




## 1. Mixed Data Types

```python
arr = np.array([1, 2, 3, "4"])

print(arr)
print(arr.dtype)
```

### Output

```text
['1' '2' '3' '4']
<U21
```

> The exact number in `<U21` can vary depending on the data.

### What Happened?

NumPy arrays are **homogeneous**, meaning all elements in a NumPy array have the same data type.

The original Python list contains:

```text
1     → integer
2     → integer
3     → integer
"4"   → string
```

NumPy cannot keep integers and strings as separate element types in the same regular array.

Therefore, NumPy **upcasts** the entire array to a type that can represent all the values.

Since strings can represent the integers:

```text
1 → "1"
2 → "2"
3 → "3"
4 → "4"
```

So the resulting array is:

```text
['1' '2' '3' '4']
```

---

## 2. Understanding `<U21`

```python
print(arr.dtype)
```

Possible output:

```text
<U21
```

Here:

- `<` → byte-order notation
- `U` → Unicode string
- `21` → maximum number of Unicode characters allocated for each element

You **do not need to memorize the exact number**.

The important point is:

> NumPy string arrays use a dtype such as `<U#`, rather than simply reporting `"str"`.

---

## 3. Boolean dtype

```python
arr2 = np.array([True, False, True])

print(arr2.dtype)
```

### Output

```text
bool
```

This is correct because all elements are Boolean values.

---

## 4. `int8` and `.itemsize`

```python
arr3 = np.array([1, 2, 3], dtype=np.int8)

print(arr3.dtype)
print(arr3.itemsize)
```

### Output

```text
int8
1
```

### Why is `itemsize` equal to `1`?

`itemsize` tells you:

> **How many bytes are used by ONE element of the array.**

It does **not** tell you how many elements are in the array.

`int8` means:

```text
8 bits
```

Since:

```text
8 bits = 1 byte
```

therefore:

```text
arr3.itemsize = 1 byte
```

### Compare Different Integer Types

| dtype | Bits per element | Bytes per element |
|-------|------------------|-------------------|
| `int8` | 8 bits | 1 byte |
| `int16` | 16 bits | 2 bytes |
| `int32` | 32 bits | 4 bytes |
| `int64` | 64 bits | 8 bytes |

### `itemsize` vs `size`

```python
arr3.size
```

gives:

```text
3
```

because there are **3 elements**.

Whereas:

```python
arr3.itemsize
```

gives:

```text
1
```

because each element occupies **1 byte**.

### Key Takeaway

> **`.size` → number of elements**

> **`.itemsize` → bytes used by each element**

> **`.dtype` → data type of the elements**

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(len(arr))
print(arr.size)
print(arr.shape[0])
print(arr.shape[1])

# (2 3)
# 6
# 3
# 3

2
6
2
3


# `len()` vs `.size` vs `.shape`

Consider this 2D NumPy array:

```python
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
```

Its shape is:

```text
(2, 3)
```

That means:

- **2 rows**
- **3 columns**

---

## 1. `len(arr)`

```python
print(len(arr))
```

### Output

```text
2
```

For a multi-dimensional NumPy array, `len()` returns the size of the **first (outermost) dimension**.

Here:

```text
2 rows → len(arr) = 2
```

### Important

`len()` always returns a **single integer**.

It does not return the complete shape.

wrong :

```text
(2, 3)
```
right :

```text
2
```

---

## 2. `arr.size`

```python
print(arr.size)
```

### Output

```text
6
```

`.size` gives the **total number of elements** in the array.

There are:

```text
2 rows × 3 columns = 6 elements
```

Therefore:

```text
arr.size = 6
```

---

## 3. `arr.shape`

```python
print(arr.shape)
```

### Output

```text
(2, 3)
```

`.shape` gives the size of every dimension.

For a 2D array:

```text
(rows, columns)
```

Therefore:

```text
shape = (2, 3)
```

---

## 4. `arr.shape[0]`

```python
print(arr.shape[0])
```

### Output

```text
2
```

Index `0` refers to the **first dimension**.

For a 2D array:

```text
shape[0] → rows
```

Therefore:

```text
arr.shape[0] = 2
```

---

## 5. `arr.shape[1]`

```python
print(arr.shape[1])
```

### Output

```text
3
```

Index `1` refers to the **second dimension**.

For a 2D array:

```text
shape[1] → columns
```

Therefore:

```text
arr.shape[1] = 3
```

---

## Summary

| Expression | Meaning | Result |
|------------|---------|--------|
| `len(arr)` | Number of rows / first dimension | **2** |
| `arr.size` | Total number of elements | **6** |
| `arr.shape` | Complete shape | **(2, 3)** |
| `arr.shape[0]` | Number of rows | **2** |
| `arr.shape[1]` | Number of columns | **3** |

###  Important Rule to Memorize

For a 2D NumPy array:

```text
shape = (rows, columns)
```

Therefore:

```text
shape[0] = rows
shape[1] = columns
```

And:

```text
len(arr) = shape[0]
```

> **`len()` → first dimension**

> **`.size` → total elements**

> **`.shape` → dimensions**

In [ ]:
original = np.array([[1, 2], [3, 4]], dtype=float)
print(np.zeros_like(original))
print(np.zeros_like(original).dtype)

# [[0.0 0.0],
#  [0.0 0.0]]

# float64

[[0. 0.]
 [0. 0.]]
float64


# `np.zeros_like()`

Suppose we have an existing array:

```python
original = np.array([[1.5, 2.5],
                     [3.5, 4.5]])
```

Now:

```python
print(np.zeros_like(original))
```

### Output

```text
[[0. 0.]
 [0. 0.]]
```

And:

```python
print(np.zeros_like(original).dtype)
```

### Output

```text
float64
```

---

## What does `zeros_like()` do?

`np.zeros_like()` creates a **new array filled with zeros** that has the:

- Same shape
- Same dtype

as the original array.

For example:

```python
original.shape
```

is:

```text
(2, 2)
```

Therefore:

```python
np.zeros_like(original)
```

also has shape:

```text
(2, 2)
```

And because `original` contains floating-point values, the new array also uses a floating-point dtype.

---

## Compare

```python
original
```

```text
[[1.5 2.5]
 [3.5 4.5]]
```

```python
np.zeros_like(original)
```

```text
[[0. 0.]
 [0. 0.]]
```

The **structure stays the same**, but the values become zero.

---

## Important Difference

### `np.zeros()`

You specify the shape:

```python
np.zeros((2, 2))
```

### `np.zeros_like()`

You specify an existing array:

```python
np.zeros_like(original)
```

NumPy automatically gets the shape and dtype from `original`.

---

## Key Takeaway

> **`np.zeros_like(arr)` → creates zeros with the same shape and dtype as `arr`.**

This is useful when you need a **blank array that matches an existing array's structure**.

In [ ]:
lst = [1, 2, 3]
arr = np.array([1, 2, 3])

print(lst * 2)
print(arr * 2)

print(lst + [4, 5])

# [2,4,6]
# [2 4 6]
# [1,2,3,4,5]

[1, 2, 3, 1, 2, 3]
[2 4 6]
[1, 2, 3, 4, 5]


#  Python List vs NumPy Array with `*`

Consider:

```python
lst = [1, 2, 3]
arr = np.array([1, 2, 3])
```

Now compare:

```python
print(lst * 2)
print(arr * 2)
```

---

## 1. Python List: `lst * 2`

```python
print(lst * 2)
```

### Output

```text
[1, 2, 3, 1, 2, 3]
```

For a normal Python list, `*` with an integer means **repetition**.

It does NOT multiply each element.

```python
[1, 2, 3] * 2
```

means:

```text
[1, 2, 3] + [1, 2, 3]
```

Result:

```text
[1, 2, 3, 1, 2, 3]
```

This is the same rule you learned with strings:

```python
"abc" * 3
```

produces:

```text
"abcabcabc"
```

---

## 2. NumPy Array: `arr * 2`

```python
print(arr * 2)
```

### Output

```text
[2 4 6]
```

NumPy performs **element-wise multiplication**.

Conceptually:

```text
[1, 2, 3] * 2
    ↓
[1×2, 2×2, 3×2]
    ↓
[2, 4, 6]
```

---

## The Important Difference

| Operation | Result | Meaning |
|-----------|--------|---------|
| `lst * 2` | `[1, 2, 3, 1, 2, 3]` | List repetition |
| `arr * 2` | `[2 4 6]` | Element-wise multiplication |

This difference is one of the most important concepts when moving from **Python lists to NumPy arrays**.

---

## 3. What About `+`?

For lists:

```python
print(lst + [4, 5])
```

### Output

```text
[1, 2, 3, 4, 5]
```

List `+` means **concatenation**.

With NumPy arrays, `+` performs **element-wise addition**.

For example:

```python
arr = np.array([1, 2, 3])
print(arr + 2)
```

Output:

```text
[3 4 5]
```

---

## Why Is This Important?

Suppose you want to double every element of a Python list.

With a list, you need something like:

```python
[x * 2 for x in lst]
```

Result:

```text
[2, 4, 6]
```

With NumPy:

```python
arr * 2
```

directly performs the operation on every element.

---

## Vectorized Operations

This is an example of a **vectorized operation**.

Instead of explicitly writing a loop:

```python
[x * 2 for x in lst]
```

NumPy lets you write:

```python
arr * 2
```

and the operation is applied to the entire array.

This is one of the major reasons NumPy is so important in:

- Data Science
- Machine Learning
- Deep Learning
- Numerical Computing

###  Key Takeaway

> **Python list `*` → repetition**

> **NumPy array `*` → element-wise multiplication**

This distinction is fundamental to understanding why NumPy is different from ordinary Python lists.

In [ ]:
arr = np.arange(12)
print(arr.reshape(3, -1))
print(arr.reshape(-1, 4))
print(arr.reshape(2, 2, -1))

# [[0 1 2 3]
#  [4 5 6 7]
#  [8 9 10 11]]
# [[0 1 2 3]
#  [4 5 6 7]
#  [8 9 10 11]]
# [[[0 1 2]
#   [3 4 5]]
#  [[6 7 8]
#   [9 10 11]]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [ ]:
arr = np.array([127, 128, 129], dtype=np.int8)
print(arr)

arr2 = np.array([100], dtype=np.int8)
arr2[0] = arr2[0] + 50
print(arr2)

# [127 128 129]
# [150]

OverflowError: Python integer 128 out of bounds for int8


## 1. `int8` Range

```python
arr = np.array([127, 128, 129], dtype=np.int8)

print(arr)
```

### Output

```text
[ 127 -128 -127]
```

### Why?

An `int8` can represent values only in this range:

```text
-128 to 127
```

| Value | Fits in `int8`? | Result |
|------:|:---------------:|-------:|
| `127` | ✅ | `127` |
| `128` | ❌ | `-128` |
| `129` | ❌ | `-127` |

`127` is the maximum value, so it stays unchanged.

But `128` and `129` are outside the allowed range.

Instead of raising an error, NumPy **wraps around** the values.

---

## 2. Understanding Wraparound

Think of the `int8` range as a cycle:

```text
-128 → -127 → ... → -1 → 0 → 1 → ... → 126 → 127
  ↑                                              ↓
  └──────────────────────────────────────────────┘
```

After reaching `127`, the next value wraps back to `-128`.

Therefore:

```text
128 → -128
129 → -127
```

This behavior comes from the fixed-width, two's-complement representation used for signed integers.

---

## 3. Overflow During Arithmetic

```python
arr2 = np.array([100], dtype=np.int8)

arr2[0] = arr2[0] + 50

print(arr2)
```

### Output

```text
[-106]
```

Mathematically:

```text
100 + 50 = 150
```

But `150` cannot be stored in `int8`.

The maximum is:

```text
127
```

So the value wraps around and becomes:

```text
-106
```

---

## 4. Why Is This Dangerous?

This is not just a quiz trick.

Suppose you deliberately use a smaller dtype to save memory:

```python
dtype=np.int8
```

That can be useful when working with very large datasets.

However, if your data exceeds the dtype's range, NumPy may silently produce incorrect values.

```text
Original value
      ↓
Outside dtype range
      ↓
Silent overflow
      ↓
Incorrect value
      ↓
Wrong results throughout the pipeline
```

There may be **no obvious error** telling you that your data has been corrupted.

This can become especially dangerous in:

- Data Science
- Machine Learning
- Large datasets
- Numerical computing
- Memory optimization

---

## 5. NumPy vs Python Integers

Python's normal `int` supports **arbitrarily large integers** (limited mainly by available memory).

For example:

```python
x = 10**100
print(x)
```

Python can represent this extremely large integer.

NumPy's fixed-width integer types, such as:

```python
np.int8
np.int16
np.int32
np.int64
```

have specific ranges.

---

## Key Takeaway

> **`int8` range = -128 to 127**

> **Values outside the range can wrap around instead of producing an error.**

> When choosing a smaller dtype for memory efficiency, make sure your data fits within its range.

**Silent overflow can lead to silently corrupted data.**

In [ ]:
print(np.arange(5) / 2)
print(np.arange(5) // 2)
print(np.arange(5, dtype=float))

# [0 0.5 1 1.5 2]
# [0 0 1 1 2]
# [0. 1. 2. 3. 4.]

[0.  0.5 1.  1.5 2. ]
[0 0 1 1 2]
[0. 1. 2. 3. 4.]


In [ ]:
arr = np.array([1.9, 2.1, 3.7, -1.5])
print(arr.astype(int))

arr2 = np.array([300, 400, 500], dtype=np.int64)
print(arr2.astype(np.int8))

# [1 2 3 -1]
# error

[ 1  2  3 -1]
[  44 -112  -12]



## 1. Converting Float to Integer

```python
arr = np.array([1.9, 2.1, 3.7, -1.5])

print(arr.astype(int))
```

### Output

```text
[ 1  2  3 -1]
```

### Important: `.astype(int)` Truncates

`.astype(int)` does **not** round the numbers to the nearest integer.

Instead, it **truncates toward zero**.

```text
 1.9  →  1
 2.1  →  2
 3.7  →  3
-1.5  → -1
```

Notice:

```text
1.9  → 1    not 2
-1.5 → -1   not -2
```

---

## 2. What If We Actually Want Rounding?

Use `np.round()` first:

```python
print(np.round(arr).astype(int))
```

For example:

```text
1.9  → 2
2.1  → 2
3.7  → 4
-1.5 → -2
```

So:

```python
arr.astype(int)
```

and:

```python
np.round(arr).astype(int)
```

are **not the same operation**.

---

# 3. Converting `int64` to `int8`

Consider:

```python
arr2 = np.array([300, 400, 500], dtype=np.int64)

print(arr2.astype(np.int8))
```

### Output

```text
[ 44 -112  -12]
```

You might expect NumPy to raise an error because these values don't fit inside `int8`.

But NumPy **silently converts them using fixed-width integer wraparound**.

---

## 4. Why?

Remember:

```text
int8 range = -128 to 127
```

But our values are:

```text
300
400
500
```

All of them are outside that range.

Therefore, when converting:

```python
arr2.astype(np.int8)
```

NumPy wraps the values around.

The results are:

```text
300 → 44
400 → -112
500 → -12
```

---

## 5. The Same Overflow Concept Appears Again

This is the same fundamental issue from integer overflow.

### Creating an `int8` array:

```python
np.array([128], dtype=np.int8)
```

can overflow.

### Casting to `int8`:

```python
np.array([128]).astype(np.int8)
```

can also produce a wrapped value.

So the important concept is:

> **NumPy does not automatically protect you when converting values to a smaller fixed-width integer dtype.**

---

## 6. Why This Matters in Real Projects

Suppose you have:

```python
arr = np.array([300, 400, 500])
```

and convert it to:

```python
arr.astype(np.int8)
```

You might be trying to save memory.

But the resulting values are no longer the original values.

```text
Original
[300, 400, 500]

      ↓ astype(np.int8)

[44, -112, -12]
```

The conversion succeeded technically, but the data became incorrect.

This can be especially dangerous in:

- Machine Learning pipelines
- Large datasets
- Data preprocessing
- Numerical calculations

because incorrect values can silently propagate through later calculations.

---

## Key Takeaway

### `.astype(int)`

> Converts values to integers by **truncating toward zero**.

### `.astype(smaller_integer_dtype)`

> Can cause **silent overflow/wraparound** when values don't fit.

Remember:

```text
.astype(int) → truncation

.astype(np.int8) → possible overflow
```

Always make sure the target dtype can represent the values you are converting.

In [ ]:
arr = np.arange(10)
print(arr.reshape(3, 4))

# error

ValueError: cannot reshape array of size 10 into shape (3,4)

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(arr1 == arr2)

if arr1 == arr2:
    print("equal")

# True
# equal

[ True  True  True]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

# Array `==` Inside an `if` Statement

## 1. Comparing Two NumPy Arrays

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

print(arr1 == arr2)
```

### Output

```text
[ True  True  True]
```

### Why?

The `==` operator performs **element-wise comparison** when used with NumPy arrays.

It compares corresponding elements:

```text
1 == 1 → True
2 == 2 → True
3 == 3 → True
```

Therefore:

```text
[ True  True  True]
```

is returned.

> **NumPy array `==` → element-wise comparison → Boolean array**

---

## 2. Why Doesn't This Work?

```python
if arr1 == arr2:
    print("equal")
```

This raises:

```text
ValueError: The truth value of an array with more than one element is ambiguous.
Use a.any() or a.all()
```

### Why?

An `if` statement needs **one single Boolean value**:

```text
True
```

or:

```text
False
```

But:

```python
arr1 == arr2
```

produces:

```text
[ True  True  True]
```

This contains **three Boolean values**.

NumPy refuses to guess what you mean:

```text
Should ALL values be True?
        OR
Should AT LEAST ONE value be True?
```

Therefore, NumPy raises an error instead of making an assumption.

---

## 3. Using `.all()`

If you want to check whether **every element matches**:

```python
if (arr1 == arr2).all():
    print("equal")
```

Output:

```text
equal
```

`.all()` returns `True` only when **every value** in the Boolean array is `True`.

Example:

```text
[True  True  True] → .all() → True

[True  False True] → .all() → False
```

---

## 4. Using `.any()`

If you want to check whether **at least one element matches**:

```python
if (arr1 == arr2).any():
    print("some match")
```

`.any()` returns `True` when **at least one value** is `True`.

Example:

```text
[False False True] → .any() → True

[False False False] → .any() → False
```

---

## 5. Using `np.array_equal()`

If your goal is simply to check whether **two arrays are completely equal**, the cleanest approach is:

```python
if np.array_equal(arr1, arr2):
    print("equal")
```

Output:

```text
equal
```

`np.array_equal()` checks:

- Shape
- Values

and returns **one Boolean value**.

---

## Summary

| Expression | What it does | Result |
|------------|--------------|--------|
| `arr1 == arr2` | Element-wise comparison | Boolean array |
| `(arr1 == arr2).all()` | Checks whether every element matches | Single `True`/`False` |
| `(arr1 == arr2).any()` | Checks whether at least one element matches | Single `True`/`False` |
| `np.array_equal(arr1, arr2)` | Checks complete array equality | Single `True`/`False` |

### Key Takeaway

> **`arr1 == arr2` gives an array of Booleans, not one Boolean.**

For complete equality, prefer:

```python
np.array_equal(arr1, arr2)
```

For conditional checks:

```python
(arr1 == arr2).all()
```

or:

```python
(arr1 == arr2).any()
```

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
print(np.array_equal(arr1, arr2))

arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([1, 2, 3, 4])
print(arr3 == arr4)

# True
# False

True


ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

# `array_equal()` and Shape-Mismatched Arrays

## 1. `np.array_equal()`

```python
print(np.array_equal(arr1, arr2))
```

### Output

```text
True
```

`np.array_equal()` checks whether two arrays have:

1. The same shape
2. The same values

It always returns **one Boolean value**:

```text
True
```

or:

```text
False
```

It does not return an array of Booleans.

---

## 2. Arrays with Different Shapes

Consider:

```python
arr3 = np.array([[1, 2],
                 [3, 4]])

arr4 = np.array([1, 2, 3, 4])
```

Their shapes are:

```python
print(arr3.shape)
print(arr4.shape)
```

### Output

```text
(2, 2)
(4,)
```

So:

```text
arr3 → shape (2, 2)
arr4 → shape (4,)
```

Now consider:

```python
print(arr3 == arr4)
```

These shapes are **not broadcast-compatible** for a clean element-wise comparison.

Depending on the NumPy version, this may:

- Raise a `ValueError`, or
- Produce a scalar `False` with a `DeprecationWarning`

The important point is:

> You should **not rely on `==` between arrays with mismatched shapes**.

---

## 3. Why Are the Shapes Incompatible?

`arr3` has:

```text
(2, 2)
```

which means:

```text
2 rows × 2 columns
```

while `arr4` has:

```text
(4,)
```

which means:

```text
1-dimensional array containing 4 elements
```

Their dimensions cannot be matched in the required way for this comparison.

---

## 4. Safe Way: `np.array_equal()`

Instead, use:

```python
print(np.array_equal(arr3, arr4))
```

### Output

```text
False
```

`np.array_equal()` handles the shape mismatch cleanly.

Since:

```text
(2, 2) ≠ (4,)
```

the arrays are not equal.

---

## Summary

| Operation | Behavior |
|-----------|----------|
| `arr1 == arr2` | Element-wise comparison |
| `np.array_equal(arr1, arr2)` | Complete equality check |
| `==` with mismatched shapes | May error / should not be relied upon |
| `np.array_equal()` with mismatched shapes | Safely returns `False` |

###  Key Takeaway

> **If you want to know whether two NumPy arrays are completely equal, use `np.array_equal()`.**

Do not depend on:

```python
arr1 == arr2
```

when the arrays may have different shapes.

In [ ]:
arr = np.array([1, 2, 3])
print(arr.dtype)

arr2 = arr / 1
print(arr2.dtype)

arr3 = np.array([1, 2, 3]) + np.array([1.0, 2.0, 3.0])
print(arr3.dtype)

# int64
# float64
# float64

int64
float64
float64


# dtype Upcasting During NumPy Operations

NumPy often needs to combine arrays or values with different data types.

When this happens, NumPy may **upcast** the result to a more general dtype that can safely represent the values.

---

## 1. Integer Array

```python
arr.dtype
```

### Output

```text
int64
```

So `arr` contains 64-bit integers.

---

## 2. Division Produces Float

```python
arr2.dtype
```

### Output

```text
float64
```

This happens because NumPy's `/` operator performs **true division**.

For example:

```python
np.array([1, 2, 3]) / 2
```

produces:

```text
[0.5 1.  1.5]
```

The result must be able to represent decimal values, so NumPy uses a floating-point dtype.

> **True division `/` → floating-point result**

---

## 3. Integer + Float

Suppose:

```python
arr3 = np.array([1, 2, 3]) + np.array([1.5, 2.5, 3.5])
```

The first array contains integers:

```text
int
```

The second contains floating-point numbers:

```text
float
```

Therefore, the result is converted to a floating-point dtype.

```python
arr3.dtype
```

### Output

```text
float64
```

---

## 4. Why Does Upcasting Happen?

NumPy arrays are homogeneous, meaning the elements of an array generally share one dtype.

When different numeric types are combined, NumPy chooses a dtype capable of representing the result.

For example:

```text
int + float
     ↓
float
```

The integer values can be represented as floats, so NumPy promotes the result to `float64`.

---

## Common Examples

| Operation | Typical Result dtype |
|-----------|----------------------|
| `int + int` | Integer |
| `int + float` | Float |
| `int / int` | Float |
| `float + float` | Float |

###  Key Takeaway

> **When NumPy performs operations between compatible but different numeric dtypes, it often upcasts the result to a more general dtype.**

A useful rule to remember:

```text
int + float → float
```

and:

```text
/ → float
```

In [ ]:
arr = np.array([1, 2, None, 4])
print(arr)
print(arr.dtype)

# [1 2 None 4]
# None

[1 2 None 4]
object


# `None` Inside a NumPy Array

Consider:

```python
arr = np.array([1, 2, None, 4])

print(arr)
print(arr.dtype)
```

### Output

```text
[1 2 None 4]
object
```

---

## 1. Why Is the dtype `object`?

Normally, NumPy tries to store arrays using an efficient numeric dtype such as:

```text
int64
float64
```

But this array contains:

```text
1     → integer
2     → integer
None  → Python None object
4     → integer
```

`None` cannot be represented using a normal integer or floating-point NumPy dtype.

Therefore, NumPy falls back to:

```text
object
```

---

## 2. What Does `object` Mean?

An object array stores references to **Python objects** rather than using one efficient fixed-width numeric representation for every element.

Conceptually:

```text
[1, 2, None, 4]
 ↓  ↓   ↓   ↓
Python objects
```

You can think of NumPy as saying:

> "These elements don't fit into one normal numeric dtype, so I'll store them as generic Python objects."

---

## 3. Why Is `object` Usually Less Efficient?

Numeric NumPy arrays are designed for:

- Contiguous memory
- Fast numerical operations
- Vectorization
- Efficient memory usage

An `object` array loses many of these advantages because its elements are Python object references.

Therefore, unexpectedly getting:

```text
dtype('O')
```

or:

```text
object
```

can be a warning sign that something unexpected entered your data.

---

## 4. NumPy vs Pandas

This distinction becomes important later when working with Pandas.

In raw NumPy:

```python
np.array([1, 2, None, 4])
```

can result in:

```text
dtype = object
```

Pandas has its own missing-data mechanisms and can handle missing values differently depending on the dtype and version.

For example, Pandas may use:

```text
NaN
```

or nullable dtypes such as:

```text
Int64
```

This is one reason you should not assume that NumPy and Pandas handle missing values identically.

---

## Summary

```python
arr = np.array([1, 2, None, 4])
```

produces:

```text
[1 2 None 4]
```

with:

```text
dtype = object
```

because `None` cannot be represented by a normal numeric dtype.

### Key Takeaway

> **`None` inside a NumPy array can cause the array to use `object` dtype.**

And:

> **Object arrays are generally less efficient for numerical computation than normal numeric NumPy arrays.**

In [ ]:
arr = np.arange(6)
reshaped = arr.reshape(2, 3)
reshaped[0, 0] = 999
print(arr)

# [[999 1 2]
#  [3 4 5]]

[999   1   2   3   4   5]


# `reshape()` Returns a View

Consider:

```python
arr = np.arange(6)
```

This creates:

```text
[0 1 2 3 4 5]
```

The shape is:

```text
(6,)
```

Now reshape it:

```python
reshaped = arr.reshape(2, 3)
```

The new array looks like:

```text
[[0 1 2]
 [3 4 5]]
```

and its shape is:

```text
(2, 3)
```

---

## 1. Modify the Reshaped Array

Now:

```python
reshaped[0, 0] = 999
```

Then:

```python
print(arr)
```

### Output

```text
[999   1   2   3   4   5]
```

Notice something important:

`arr` is still **1-dimensional**.

It did NOT become:

```text
[[999 1 2]
 [3 4 5]]
```

Its shape is still:

```text
(6,)
```

---

## 2. Why Did `arr` Change?

Because `reshape()` can return a **view** of the original array rather than creating a completely independent copy.

Conceptually:

```text
             Same underlying data
                    ↓
        ┌─────────────────────┐
        │ 0 1 2 3 4 5         │
        └─────────────────────┘
             ↑           ↑
             │           │
          arr          reshaped
         (6,)          (2,3)
```

The two array objects have different shapes, but they can point to the **same underlying memory**.

Therefore:

```python
reshaped[0, 0] = 999
```

changes the shared underlying data.

So:

```python
print(arr)
```

shows:

```text
[999   1   2   3   4   5]
```

---

## 3. Shape Is Not Shared

This is extremely important.

`arr`:

```text
shape = (6,)
```

`reshaped`:

```text
shape = (2, 3)
```

Changing the shape of the view does **not** change the shape of the original array.

So:

```text
arr       → 1D
reshaped  → 2D
```

at the same time.

What they share is the **underlying data**, not the shape.

---

## 4. Connection to List Aliasing

This is similar to the aliasing concept you saw with Python variables and lists.

For example:

```python
a = [1, 2, 3]
b = a

b[0] = 999

print(a)
```

Output:

```text
[999, 2, 3]
```

Both variables refer to the same underlying list.

NumPy views follow a related idea:

```text
Different array objects
        ↓
Same underlying data
        ↓
Mutation through one can affect the other
```

---

## 5. View vs Copy

### View

A view shares the underlying data:

```text
Original ─────┐
              ↓
          Same memory
              ↑
View ─────────┘
```

Changing one can affect the other.

### Copy

A copy creates independent data:

```text
Original → Memory A

Copy     → Memory B
```

Changing the copy does not change the original.

---

## 6. Why This Matters

This behavior is extremely important in NumPy and later in Machine Learning workflows.

Several NumPy operations can return **views**, including:

- `reshape()` in many cases
- Slicing
- Some transpose-related operations
- Other operations that can avoid copying data

If you accidentally modify a view, you may unintentionally modify the original data.

That can lead to difficult-to-find bugs in data preprocessing and ML pipelines.

---

## Summary

| Object | Shape | Underlying data |
|--------|-------|-----------------|
| `arr` | `(6,)` | Shared |
| `reshaped` | `(2, 3)` | Shared |

After:

```python
reshaped[0, 0] = 999
```

we get:

```text
arr
→ [999 1 2 3 4 5]

reshaped
→ [[999 1 2]
   [3 4 5]]
```

###  Key Takeaway

> **A NumPy view can have a different shape from the original while still sharing the same underlying data.**

Therefore:

> **Mutating a view can also mutate the original array.**

This is one of the most important NumPy concepts to understand before moving into **Views vs Copies**.